parameters:
  appUrl: ''

steps:
  - script: |
      docker compose up -d
    displayName: "CD - docker compose up"

  - script: |
      sleep 5
      curl -f "${{ parameters.appUrl }}"
    displayName: "E2E"

  - script: |
      docker compose down --volumes || true
    displayName: "CD - docker compose down"
    condition: always()
