# Template (Azure Pipelines) - CI Python (steps)
#
# Este template es un punto de partida para reutilizar steps de CI en varios repos.
# En la Práctica 5 se pide que ambos proyectos consuman templates desde el repo IaC.

parameters:
  pythonImage: "python:3.6-slim"

steps:
  - script: |
      docker run --rm \
        -v $(pwd):/app \
        -w /app \
        --user $(id -u):$(id -g) \
        ${{ parameters.pythonImage }} \
        sh -c "pip install -q -r requirements.txt && flake8 src/ && python -m black -l 79 -t py311 --check src/ tests/"
    displayName: "Lint (flake8 + black)"
  - script: |
      docker run --rm \
        -v $(pwd):/app \
        -w /app \
        --user $(id -u):$(id -g) \
        ${{ parameters.pythonImage }} \
        sh -c "pip install -q -r requirements.txt && coverage run -m pytest -v --tb=short --maxfail=1 tests/"
    displayName: "Test (pytest + coverage)"
