# Template (Azure Pipelines) - CI SonarQube Analysis (steps)
parameters:
  mavenImage: "maven:3.8.6-openjdk-11-slim"
  sonarHostUrl: "http://192.168.50.201:9000"
  sonarProjectKey: "DevOps"
  sonarToken: ""

steps:
  - script: |
      docker run --rm \
        -v $(pwd):/app \
        -w /app \
        --user $(id -u):$(id -g) \
        -e MAVEN_OPTS="-Dmaven.repo.local=/app/.m2" \
        --network host \
        ${{ parameters.mavenImage }} \
        mvn -q -Dmaven.repo.local=/app/.m2 sonar:sonar \
          -Dsonar.projectKey=${{ parameters.sonarProjectKey }} \
          -Dsonar.host.url=${{ parameters.sonarHostUrl }} \
          -Dsonar.token=${{ parameters.sonarToken }}
    displayName: "SonarQube Analysis"
