# Template (Azure Pipelines) - CI SonarQube Analysis (steps)
# Reemplazamos mavenImage compatible con Java17
# Añadimos paso de compilación
# Añadimos JaCoCo coverage report
parameters:
  mavenImage: "maven:3.9-eclipse-temurin-17"
  sonarHostUrl: "http://192.168.50.201:9000"
  sonarProjectKey: "DevOps"
  sonarToken: ""

steps:
  - task: DownloadPipelineArtifact@2
    displayName: "Descargar reporte JaCoCo"
    inputs:
      artifactName: "jacoco-report"
      targetPath: "$(System.DefaultWorkingDirectory)/target/site/jacoco"

  - script: |
      docker run --rm \
        -v $(pwd):/app \
        -w /app \
        --user $(id -u):$(id -g) \
        -e MAVEN_OPTS="-Dmaven.repo.local=/app/.m2" \
        ${{ parameters.mavenImage }} \
        mvn -q -Dmaven.repo.local=/app/.m2 compile -DskipTests
    displayName: "Compilar antes del análisis"

  - script: |
      docker run --rm \
        -v $(pwd):/app \
        -w /app \
        --user $(id -u):$(id -g) \
        -e MAVEN_OPTS="-Dmaven.repo.local=/app/.m2" \
        --network host \
        ${{ parameters.mavenImage }} \
        mvn -q -Dmaven.repo.local=/app/.m2 sonar:sonar \
          -Dsonar.projectKey=${{ parameters.sonarProjectKey }} \
          -Dsonar.host.url=${{ parameters.sonarHostUrl }} \
          -Dsonar.token=${{ parameters.sonarToken }} \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.sources=src/main/java \
          -Dsonar.tests=src/test/java \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
    displayName: "SonarQube Analysis"
